# Generated by Django 5.2 on 2025-09-17 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjektList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objekts', models.ManyToManyField(blank=True, related_name='objekt_list', to='objekt.objektcard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objekt_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
