# Generated by Django 5.2 on 2025-09-16 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekt', '0002_alter_season_shortname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjektList',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objekts', models.ManyToManyField(related_name='objekt_list', to='objekt.objektcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objekt_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
