# Generated by Django 5.2 on 2025-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objektlist',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='objektlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
