# Generated by Django 5.2 on 2025-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('objekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objektlist',
            name='objekts',
            field=models.ManyToManyField(blank=True, related_name='objekt_list', to='objekt.objekttype'),
        ),
    ]
