# Generated by Django 5.2 on 2025-09-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tokenId', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['tokenId'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('collection_number', models.CharField(blank=True, max_length=20, null=True)),
                ('collection_suffix', models.CharField(max_length=20, null=True)),
                ('physical', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startNum', models.IntegerField(null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='objekt.artist')),
            ],
            options={
                'ordering': ['artist', 'startNum'],
                'unique_together': {('name', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('memberCode', models.CharField(blank=True, max_length=50, null=True)),
                ('memberNum', models.IntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='objekt.artist')),
            ],
            options={
                'ordering': ['memberNum'],
            },
        ),
        migrations.CreateModel(
            name='ObjektType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uri', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objekt.artist')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objekt.collection')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objekt.member')),
                ('objekt_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objekt.class')),
            ],
            options={
                'ordering': ['artist', 'collection', 'member'],
            },
        ),
        migrations.CreateModel(
            name='ObjektCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.BigIntegerField(unique=True)),
                ('owner_address', models.CharField(max_length=200)),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objekt_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objekt.objekttype')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('seasonPrefix', models.CharField(max_length=50)),
                ('seasonNum', models.IntegerField()),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='objekt.artist')),
            ],
            options={
                'ordering': ['artist', 'startDate'],
                'unique_together': {('name', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='objekttype',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objekt.season'),
        ),
    ]
