# Generated by Django 5.2 on 2025-09-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='objekt.artist'),
        ),
    ]
