# Generated by Django 5.2 on 2025-09-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
