# Generated by Django 5.2 on 2025-09-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0002_alter_member_membercode_alter_member_membernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
