# Generated by Django 5.2 on 2025-09-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0002_alter_member_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='objekt.artist'),
        ),
        migrations.AlterField(
            model_name='class',
            name='startNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_number',
            field=models.IntegerField(null=True),
        ),
    ]
