# Generated by Django 5.2 on 2025-09-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0003_alter_member_membercode_alter_member_membernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='objekt.artist'),
        ),
    ]
