# Generated by Django 5.2 on 2025-09-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0003_alter_class_artist_alter_class_startnum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_number',
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_number_int',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_suffix',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
