# Generated by Django 5.2 on 2025-09-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0004_remove_collection_collection_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_number_int',
            new_name='collection_number',
        ),
    ]
