# Generated by Django 5.2 on 2025-09-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objekt', '0005_rename_collection_number_int_collection_collection_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='debutDate',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='debutYear',
        ),
    ]
